name: Deploy
on: [push,workflow_dispatch]
jobs: 
    greet: 
        runs-on: ubuntu-latest
        steps: 
            - name: "Get code"
              uses: actions/checkout@v4
            - name: Install Node 20
              uses: actions/setup-node@v4        
              with:
                node-version: 20
            - name: Print node version
              run: node -v         